### PR TITLE
Added single generics support

### PR DESCRIPTION
**Pull request by meriouma**
This adds single generics support to JSON (See JsonGenericsTests to see how it can be used)
- Added a generator that generates the JsonReader, JsonWriter, XmlWriter and XmlReader interfaces and GWT.create calls to reduce boilerplate, especially with generics.
- Changed the "newConcreteTypes" velocity macro to use GWT.create on the Reader/Writer instead of "new Model()", because sometime the serializer needed for the embedded object is not in the same package or the default constructor is not public. This ensures the Reader or Writer is created

### CODE REVIEW

**Comment by hpehl** [comment]
Wow. Great work! Thanks for the contribution. The build passed so I'll pull this in.

**Comment by christiangoudreau** [comment]
Can you plan a release ? :D

**Comment by hpehl** [comment]
Thanks for the latest contributions! Will release 0.9 in the next days. Stay tuned...

**Comment by hpehl** [comment]
Just released Piriti 0.9: https://github.com/hpehl/piriti/wiki/Releasenotes. It's available in Maven Central

**Comment by meriouma** [comment]
Thank you @hpehl ! I just saw your release notes, I only added the generics support in the json templates, though it wouldn't be too hard for someone to reproduce it in the xml templates

**Pull request merged**
